# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-21 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant_name', models.CharField(max_length=200)),
                ('assistant_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend_teacher_id', models.IntegerField(default=0)),
                ('recommend_teacher_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField(default=0)),
                ('teacher_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_password', models.CharField(max_length=100)),
                ('student_major', models.CharField(default='计算机', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentEssay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_essay_title', models.CharField(max_length=200)),
                ('student_essay_text', models.CharField(max_length=1000000)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomm.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=200)),
                ('teacher_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherEssay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_essay_title', models.CharField(max_length=200)),
                ('teacher_essay_text', models.CharField(max_length=1000000)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomm.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherFigure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure', models.TextField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomm.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='relation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomm.Student'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='student_essay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomm.StudentEssay'),
        ),
    ]
